// -------------------------------------------------------------
//
// Module: cic3
// Generated by MATLAB(R) 23.2 and Filter Design HDL Coder 23.2.
// Generated on: 2024-05-02 15:46:09
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// FIRAdderStyle: tree
// OptimizeForHDL: on
// TargetDirectory: D:\fax\zavrsni\CIC3
// AddPipelineRegisters: on
// Name: cic3
// TargetLanguage: Verilog
// TestBenchName: cic3_tb
// TestBenchStimulus: step chirp 
// LoopUnrolling: on

// Filter Specifications:
//
// Sample Rate          : 2.822 MHz
// Response             : CIC Compensator
// Specification        : Fp,Fst,Ap,Ast
// Interpolation Factor : 2
// Multirate Type       : Interpolator
// Number of Sections   : 1
// Passband Edge        : 22.05 kHz
// Passband Ripple      : 0.001 dB
// Differential Delay   : 1
// Stopband Edge        : 1.389 MHz
// Stopband Atten.      : 23 dB
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Multirate Filter (real)
// -----------------------------------------
// Filter Structure      : Direct-Form FIR Polyphase Interpolator
// Interpolation Factor  : 2
// Polyphase Length      : 2
// Filter Length         : 4
// Stable                : Yes
// Linear Phase          : Yes (Type 2)
//
// Arithmetic            : fixed
// Numerator             : s16,14 -> [-2 2)
// -------------------------------------------------------------




//`timescale 1 ns / 1 ns

module cic3
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out,
                ce_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [17:0] filter_in; //sfix18_En15
  output  signed [16:0] filter_out; //sfix17_En15
  output  ce_out; 

////////////////////////////////////////////////////////////////
//Module Architecture: cic3
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeffphase1_1 = 16'b1111011011111011; //sfix16_En14
  parameter signed [15:0] coeffphase1_2 = 16'b0100100100000101; //sfix16_En14
  parameter signed [15:0] coeffphase2_1 = 16'b0100100100000101; //sfix16_En14
  parameter signed [15:0] coeffphase2_2 = 16'b1111011011111011; //sfix16_En14

  // Signals
  reg  [1:0] cur_count; // ufix2
  wire phase_1; // boolean
  reg  signed [17:0] delay_pipeline [0:1] ; // sfix18_En15
  wire signed [33:0] product; // sfix34_En29
  wire signed [15:0] product_mux; // sfix16_En14
  wire signed [33:0] product_1; // sfix34_En29
  wire signed [15:0] product_mux_1; // sfix16_En14
  wire signed [34:0] sum1; // sfix35_En29
  wire signed [33:0] add_signext; // sfix34_En29
  wire signed [33:0] add_signext_1; // sfix34_En29
  wire signed [16:0] output_typeconvert; // sfix17_En15
  reg  signed [16:0] output_register; // sfix17_En15

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: ce_output
      if (reset == 1'b1) begin
        cur_count <= 2'b00;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (cur_count >= 2'b01) begin
            cur_count <= 2'b00;
          end
          else begin
            cur_count <= cur_count + 2'b01;
          end
        end
      end
    end // ce_output

  assign  phase_1 = (cur_count == 2'b01 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  //   ---------------- Delay Registers ----------------

  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
        end
      end
    end // Delay_Pipeline_process


  assign product_mux = (cur_count == 2'b00) ? coeffphase1_2 :
                      coeffphase2_2;
  assign product = delay_pipeline[1] * product_mux;

  assign product_mux_1 = (cur_count == 2'b00) ? coeffphase1_1 :
                        coeffphase2_1;
  assign product_1 = delay_pipeline[0] * product_mux_1;

  assign add_signext = product;
  assign add_signext_1 = product_1;
  assign sum1 = add_signext + add_signext_1;

  assign output_typeconvert = ((sum1[34] == 1'b0 & sum1[33:30] != 4'b0000) || (sum1[34] == 1'b0 && sum1[30:14] == 17'b01111111111111111) // special case0
) ? 17'b01111111111111111 : 
      (sum1[34] == 1'b1 && sum1[33:30] != 4'b1111) ? 17'b10000000000000000 : (sum1[30:0] + {sum1[14], {13{~sum1[14]}}})>>>14;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign ce_out = phase_1;
  assign filter_out = output_register;
endmodule  // cic3
